spring:
  profiles:
    active: local
    include:
      - secret #application-secret.yml에 내 smtp정보 전부 저장 (gitignore처리)
  redis:
    host: localhost
    port: 6379

server:
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-alias: saechim
    key-store-password: 940215
  http2:
    enabled: true
---

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/authlocal
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  config:
    activate:
      on-profile: mysql